name: smart_city_transport
description: Autonomous vehicle rental application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI & Animations
  lottie: ^3.1.0
  flutter_svg: ^2.0.9

  # Maps
  google_maps_flutter: ^2.5.0

  # Camera & Permissions
  camera: ^0.10.5+5
  permission_handler: ^11.0.1
  image_picker: ^1.0.4

  # State Management
  provider: ^6.1.1
  shared_preferences: ^2.2.2

  # Utilities
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  # Add your assets here
  assets:

  fonts:
    - family: Inter
      fonts:
        - asset: fonts/Inter_24pt-Regular.ttf
        - asset: fonts/Inter_24pt-Bold.ttf
          weight: 700