// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQ1lpUuATAOKNZ_QtTgdkpVCyo1jtCQN4',
    appId: '1:406514704389:android:ef139c028d6eb58ac3fc6c',
    messagingSenderId: '406514704389',
    projectId: 'sdv-ota-system',
    databaseURL: 'https://sdv-ota-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sdv-ota-system.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAIrsyoTmxFoYoa-YdIaHP5oxeAQeF8TiE',
    appId: '1:406514704389:ios:a6dd5864468da55bc3fc6c',
    messagingSenderId: '406514704389',
    projectId: 'sdv-ota-system',
    databaseURL: 'https://sdv-ota-system-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'sdv-ota-system.firebasestorage.app',
    iosBundleId: 'com.kynetic.sdv',
  );

}